name: Lekcja 38 - Zadanie 12

on:
  push:

jobs:
  test-and-deploy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest homework/lesson38/zadanie4/tests/test_math.py

      - name: Ready to deploy
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: echo "Ready to deploy!"
