name: Lekcja 38 - Zadanie 8

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger
        run: echo "Workflow uruchomiony poprawnie!"
