name: Lekcja 38 - Zadanie 6

on:
  push:

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest homework/lesson38/zadanie4/tests/test_math.py
